title = "Hugo Xterm"
languageCode = "en-us"
baseurl = "https://manid2.github.io/hugo-xterm/"
paginate = 20

[module]
  [[module.imports]]
    path = "github.com/manid2/hugo-xterm"

[params]
  centerTheme = true
  showMenuItems = true
  favicon = "/images/xterm.png"
  showBreadCrumbs = true
  toc = true
  copyrightUserUrl = "https://manid2.gitlab.io/"
  copyrightUserText = "Mani Kumar"

[params.twitter]
  creator = "mani_d2"

[params.site_verification]
  google = "dRxlQUCTcreupAiAU9R-WcImzIL5ZkXVFT4PVPDJl6Y"
  bing = "F82FFC97299503C8B6340178FE5F1EFA"
  yandex = "146d77656fc95385"
  naver = "e3b93136c43487a12e31584cf30306a269137968"

[languages]
  [languages.en.params]
    copyright = "© Mani Kumar"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Home"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "cv"
        name = "CV"
        url = "/cv/"

      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"

      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
